---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherapi
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: weatherapibackend
    spec:
      containers:
      - name: weatherapi
        image: akhan2017/weatherapi
        ports:
        - containerPort: 8080
  selector:
    matchLabels:
      app: pizzabackend
---
apiVersion: v1
kind: Service
metadata:
  name: weatherapi
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: weatherapibackend